[[case_studies]]
==  Introducing our case studies


Machine learning can happen on many different types of data, and the approaches and tools may differ.
For the rest of the book, when possible, we will use data from these three case studies to explore Kubeflow and some of it's components.



=== GitHub Data

GitHub is one of the largest open collections of source code, and the wonderful folks at link:$https://www.gharchive.org/$[GH Archive] have created and archive of all of the public interactions on GitHub.
This data has been used for many interesting machine learning projects, including
link:$https://towardsdatascience.com/how-to-create-data-products-that-are-magical-using-sequence-to-sequence-models-703f86a231f8$[issue summarization] and
link:$https://githubengineering.com/towards-natural-language-semantic-code-search/$[semantic language code search] both with Kubeflow.
Using the public link:$https://www.gharchive.org/$[GitHub archive dataset] we will explore training two different models: one to generate "good" commit messages and another to predict chunks of code likely to result in a comment.


This dataset is available to us in two different ways.
The raw dataset is stored as json records on `data.gharchive.org`, and also loaded into link:$https://developers.google.com/bigquery/$[Google BigQuery]
as a link:$https://bigquery.cloud.google.com/table/githubarchive:day.20150101$[public dataset] we can write SQL expressions against.


=== Financial Data (Order Book)

=== Connected City / IoT Data

Connected cities are becoming more and more of a thing as we enter an Internet of Things World.  For this example we are
going to look at the connected city of Chicago because they are one of the most connected cities in the world, and the
pizza available there is orders of magnitude better than all other connected cities (in this author's totally unbiased
opinion).

In this example we will be considering a plethora of sources including

- https://arrayofthings.docs.apiary.io/#[Array of Things]: Which are nodes throughout Chicago measuring temperature, humidity, light, and particulant matter.
- https://www.divvybikes.com/system-data[Divvy Bike Shares] and https://www.transitchicago.com/data/[The Chicago Transit Authority] (data on busses and trains).
- http://311api.cityofchicago.org[Chicago 311 Requests]: 311 is a non-emergency hotline.
- https://dev.socrata.com/foundry/data.cityofchicago.org/n4j6-wkkf[Chicago Traffic Congestion]: Even though we have one of the best public trasportation systems in the country, suburbanites still love to drive.
- And more!




=== Conclusion

These case studies will continue throughout the book, with each one showing you how different and similar ML pipelines can be.
