[preface]
== Preface

We wrote this book for data engineers and data scientist who are building machine learning systems/models they want to productionize. If you've ever had the experience of training an excellent model only to ask your self how to deploy it into production or keep it up to date once it gets there, this is the book for you.
We hope this gives you the tools to replace `Untitled_5.ipynb` with something that works relatively reliably in production.


This book is not intended to serve as your first introduction to machine learning, <<assumptions_about_the_audience>> has pointers to some resources that may be useful if you are just getting started on your machine learning journey.


[[assumptions_about_the_audience]]
=== Our assumption about you


This book assumes that you either understand how to train models locally, or are working with someone who does. If you don't, there are many excellent introduction books on machine learning to get you started, including link:$$https://amzn.to/2WPOGJj$$["Hands-On Machine Learning with Scikit-Learn and TensorFlow: Concepts, Tools, and Techniques to Build Intelligent Systems" by Aurélien Géron].


We also assume you have the tools, or work with someone who does, to get the data needed for training your models. If you don't pass:[<a class="orm:hideurl" href="http://shop.oreilly.com/product/0636920028512.do"><em>Learning Spark</em> by Karau, Konwinski, Wendell, and Zaharia</a>] is an excellent introduction to Apache Spark, one of the most popular big data tools.footnote:[Though we may be biased.].


// TODO -- More resources here

Containers and Kubernetes are a wide area of practice, which is rapidly evolving.
If you want to deepen your knowledge of Kubernetes we recommend looking at link:$$https://amzn.to/2EdYoho$$[Cloud Native Infrastructure: Patterns for Scalable Infrastructure and Applications in a Dynamic Environment by  Justin Garrison  and Kris Nova], or link:$$https://amzn.to/2EfiRTi$$[Kubernetes: Up and Running: Dive into the Future of Infrastructure by  Kelsey Hightower, Brendan Burns, and Joe Beda].
// TODO (holden)

=== Your responsibility as a practitioner

This book helps you put your machine learning models into production and solve real world problems. Solving real world problems with machine learning is great, but as you go forth and apply your skills to the real world, remember to think about the impact.


First, it's important to make sure your models are sufficiently accurate, and there are great tools for this in Kubeflow covered in <<model_management>>.
Even the best tools will not save you from all mistakes, for example hyper-parameter tuning on the same dataset to report final cross-validation results.


Even models with great predictive power can still have unintended effects and biases that may not show up during the regular training-evaluation phase.
Unintended biases can be hard to discover, but there are many stories (e.g. link:$$https://www.reuters.com/article/us-amazon-com-jobs-automation-insight/amazon-scraps-secret-ai-recruiting-tool-that-showed-bias-against-women-idUSKCN1MK08G$$[Amazon's machine learning system which decided to only higher men]) that demonstrate the profound
potential implications of our work.



While this book does not have the tools to solve bias, we encourage you to think critically about potential biases in your system and explore solutions *before going into production*.
If you don't know where to start, Katharine Jarmul has an excellent introductory talk at link:$$https://www.thestrangeloop.com/2018/privacy-the-last-stand-for-fair-algorithms.html$$[].
One important step to helping reduce bias in your models is having a diverse team to notice potential issues early.

// TODO -- follow up with Mr. Bigg's for the college project story

[TIP]
====
And it's important to note that none of these tasks are a "one-stop", model performance can degrade, and biases can be introduced over time -- even if you don't personally change anything. footnote:[Remember the twitter bot that became a Nazi with reinforcement learning in less than a weekend?]
====


=== Conventions Used in This Book

The following typographical conventions are used in this book:

_Italic_:: Indicates new terms, URLs, email addresses, filenames, and file extensions.

+Constant width+:: Used for program listings, as well as within paragraphs to refer to program elements such as variable or function names, databases, data types, environment variables, statements, and keywords.

**`Constant width bold`**:: Shows commands or other text that should be typed literally by the user.

_++Constant width italic++_:: Shows text that should be replaced with user-supplied values or by values determined by context.


[TIP]
====
This element signifies a tip or suggestion.
====

[NOTE]
====
This element signifies a general note.
====

[WARNING]
====
This element indicates a warning or caution.
====

We will use warnings to indicate any situations where the resulting pipeline is likely to be non-portable and call out portable alternatives that you can use.

=== Code Examples
++++
<!--PROD: Please reach out to author to find out if they will be uploading code examples to oreilly.com or their own site (e.g., GitHub). If there is no code download, delete this whole section. If there is, when you email digidist with the link, let them know what you filled in for title_title (should be as close to book title as possible, i.e., learning_python_2e). This info will determine where digidist loads the files.-->
++++

Supplemental material (code examples, exercises, etc.) is available for download at link:$$https://github.com/intro-to-ml-with-kubeflow$$[]. These code examples are available under an Apache 2 license, or as described in <<using_code_examples>> at your choice.


There are additional examples under their own respective licenses that you may find useful.
The Kubeflow project it's self has an example repo at link:$$https://github.com/kubeflow/examples$$[], which at the time of the writing is available under an Apache 2 license.
Canonical also has a set of resources at link:$$https://github.com/canonical-labs/kubeflow-tools$$[] which may be of special interest to MicroK8s users.

[[using_code_examples]]
==== Using Code Examples

This book is here to help you get your job done. In general, if example code is offered with this book, you may use it in your programs and documentation. You do not need to contact us for permission unless you’re reproducing a significant portion of the code. For example, writing a program that uses several chunks of code from this book does not require permission. Selling or distributing a CD-ROM of examples from O’Reilly books does require permission. Answering a question by citing this book and quoting example code does not require permission. Incorporating a significant amount of example code from this book into your product’s documentation does require permission.

Additional details on license can be found in the repos.

We appreciate, but do not require, attribution. An attribution usually includes the title, author, publisher, and ISBN. For example: “_Book Title_ by Some Author (O’Reilly). Copyright 2012 Some Copyright Holder, 978-0-596-xxxx-x.”

If you feel your use of code examples falls outside fair use or the permission given above, feel free to contact us at pass:[<a class="email" href="mailto:permissions@oreilly.com"><em>permissions@oreilly.com</em></a>].

=== O'Reilly Safari

[role = "safarienabled"]
[NOTE]
====
pass:[<a href="http://oreilly.com/safari" class="orm:hideurl"><em class="hyperlink">Safari</em></a>] (formerly Safari Books Online) is a membership-based training and reference platform for enterprise, government, educators, and individuals.
====

Members have access to thousands of books, training videos, Learning Paths, interactive tutorials, and curated playlists from over 250 publishers, including O’Reilly Media, Harvard Business Review, Prentice Hall Professional, Addison-Wesley Professional, Microsoft Press, Sams, Que, Peachpit Press, Adobe, Focal Press, Cisco Press, John Wiley & Sons, Syngress, Morgan Kaufmann, IBM Redbooks, Packt, Adobe Press, FT Press, Apress, Manning, New Riders, McGraw-Hill, Jones & Bartlett, and Course Technology, among others.

For more information, please visit pass:[<a href="http://oreilly.com/safari" class="orm:hideurl"><em>http://oreilly.com/safari</em></a>]. 

=== How to Contact the Authors

For feedback, email us at pass:[<a class="email" href="mailto:intro-to-ml-kubeflow@googlegroups.com"><em>intro-to-ml-kubeflow@googlegroups.com</em></a>]. For random ramblings, occasionally about Kubeflow, follow us on twitter:

Holden: On Twitter at link:$$http://twitter.com/holdenkarau$$[], YouTube link:$$https://www.youtube.com/user/holdenkarau$$, Twitch link:$$https://www.twitch.tv/holdenkarau$$[], LinkedIn link:$$https://www.linkedin.com/in/holdenkarau$$[], Blog link:$$http://blog.holdenkarau.com/$$[], or Facebook link:$$https://www.facebook.com/hkarau$$[].

// TODO everyone here
// TODO(richard)
// TODO(trevor)
// TODO(ilan)

[TIP]
====
Early feedback can make a huge difference in the direction and quality of the book. We want to hear from you, especially if there are things you find confusing or wish we covered.
====


=== How to Contact Us

Please address comments and questions concerning this book to the publisher:

++++
<ul class="simplelist">
  <li>O’Reilly Media, Inc.</li>
  <li>1005 Gravenstein Highway North</li>
  <li>Sebastopol, CA 95472</li>
  <li>800-998-9938 (in the United States or Canada)</li>
  <li>707-829-0515 (international or local)</li>
  <li>707-829-0104 (fax)</li>
</ul>
++++

We have a web page for this book, where we list errata, examples, and any additional information. You can access this page at link:$$http://www.oreilly.com/catalog/<catalog page>$$[].

++++
<!--Don't forget to update the link above.-->
++++

To comment or ask technical questions about this book, send email to pass:[<a class="email" href="mailto:bookquestions@oreilly.com"><em>bookquestions@oreilly.com</em></a>].

For more information about our books, courses, conferences, and news, see our website at link:$$http://www.oreilly.com$$[].

Find us on Facebook: link:$$http://facebook.com/oreilly$$[]

Follow us on Twitter: link:$$http://twitter.com/oreillymedia$$[]

Watch us on YouTube: link:$$http://www.youtube.com/oreillymedia$$[]

=== Acknowledgments

Holden would like to thank Kris Nova for her help debugging her first Kubeflow PR, as well as the entire Kubeflow community for being so welcoming.

++++
<!--Fill in...-->
++++
