version: 2

apt-run:  &apt-install
  name: Install apt packages
  command: |
    sudo apt-get -qq update
    sudo apt-get install -y \
      shellcheck

jobs:
  build:
    working_directory: ~/mermaid-starter
    docker:
      - image: circleci/python:3.6-jessie-node-browsers-legacy
    steps:
      - checkout
      - run: *apt-install
      - run:
        name: Run our basic shell CI
        command: ./ci.sh